### ISSUE TITLE
'AbstractCursor' does not implement interface member 'ICursor.Extras.set'

### ISSUE THREAD

**Issue by diogosapessoa** [smstuebe/xamarin-sqlcipher#2]
following steps from http://stackoverflow.com/questions/35552985/xamarin-c-sharp-jar-wrapping

im using visual studio 2015 and that error appears, any suggestion ?

**Comment by smstuebe** [comment]
Usually this error occurs, when the binding generator doesn't create the correct override. You can look at the generated code of AbstractCursor search for the property Extras and look whats wrong.

**Comment by diogosapessoa** [comment]
When change "Compile using Android version:" to "Android 4.0.3 (Ice Cream Sandwich)" the error disappear
